version: 2
updates:
  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      dependencies:
        update-types:
          - "minor"
          - "patch"
